# Generated by Django 2.1.1 on 2019-06-24 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(default='', max_length=300)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante', models.TextField()),
                ('fecha', models.DateField(auto_now=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuentas.Cuenta')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='localidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cuentas.Localidad'),
        ),
    ]
